# Generated by Django 3.1.5 on 2021-01-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CamApp', '0002_auto_20210115_0104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
